In [8]:
from  gensim.models import Word2Vec

In [13]:
model =Word2Vec.load('word2vec.model')

In [26]:
model.wv['E5400']

array([-3.59417661e-03,  2.07022880e-03,  6.04275893e-03, -1.26068434e-02,
       -4.37449384e-03,  1.49727217e-03, -3.82753019e-03,  6.05579792e-03,
       -6.20372780e-03,  1.42551130e-02,  6.12995727e-03,  6.30519260e-03,
       -1.15612317e-02, -6.43875310e-03,  4.23624460e-03, -2.57948181e-03,
       -1.30149408e-03, -1.65051613e-02, -2.14457233e-02, -4.81331022e-03,
       -4.12908616e-03, -2.09821621e-03,  6.52152253e-03,  1.47381909e-02,
       -4.44527576e-03, -9.66910273e-03, -2.01375913e-02,  1.08877122e-02,
       -9.25090723e-03, -2.10650191e-02,  1.97466742e-03,  3.24870204e-03,
       -1.02697602e-02,  1.19036324e-02,  8.48866161e-03, -2.89096055e-03,
        4.51954501e-03,  2.23821681e-03, -3.56669142e-03, -8.10818281e-03,
       -3.82483297e-04, -8.65717325e-03, -3.08550745e-02,  1.35487961e-02,
        5.17876353e-04, -8.29671230e-03, -5.29294414e-03,  4.55182540e-04,
       -4.43958119e-03,  3.35906446e-03, -5.57487192e-06,  5.22061158e-03,
       -8.82637780e-03,  

In [15]:
import numpy as np

In [20]:
ss=np.load('word2vec.model.wv.vectors.npy',allow_pickle=True)

In [22]:
ss[:100]

array([[-0.02359517, -0.05242233, -0.8664274 , ...,  0.6441649 ,
        -0.55892164,  0.15335952],
       [-0.6141922 , -0.5998572 ,  0.4482675 , ...,  1.3638214 ,
        -0.7240412 ,  0.0232727 ],
       [ 0.00661711,  0.04924089, -0.5143606 , ...,  0.74503344,
        -0.4582439 , -0.2388278 ],
       ...,
       [-1.4593675 , -0.01130373,  0.53268707, ...,  0.1975343 ,
        -0.26084477, -0.16352686],
       [-0.38998675, -0.18279536, -1.1813173 , ...,  0.6601729 ,
        -1.0073886 ,  0.2075407 ],
       [-1.3062333 ,  0.6582056 , -0.11980208, ...,  0.7939008 ,
         0.1471092 ,  0.94492054]], dtype=float32)

In [44]:
ss.shape

(50901, 256)

In [24]:
tt=np.load('word2vec.model.trainables.syn1neg.npy',allow_pickle=True)

In [25]:
tt[:10]

array([[-0.17659804, -0.16147603,  0.05334844, ..., -0.22871614,
        -0.04027667, -0.20512746],
       [-0.39779222,  0.2623025 , -0.03683059, ..., -0.2489004 ,
         0.12679803,  0.09707696],
       [-0.0581267 , -0.17809437, -0.10093466, ..., -0.07720412,
        -0.10125669, -0.2306803 ],
       ...,
       [ 0.08062602, -0.04684081,  0.2797248 , ..., -0.03263376,
         0.08349566, -0.00235847],
       [-0.15031837, -0.26327458,  0.09124587, ..., -0.2592912 ,
         0.03411037, -0.3507421 ],
       [ 0.3131519 , -0.14420985, -0.11638103, ..., -0.5763021 ,
        -0.06522456, -0.27614233]], dtype=float32)

In [45]:
model.wv.index2word

['，',
 '的',
 '。',
 '了',
 '是',
 '我',
 ',',
 ' ',
 '！',
 '很',
 '也',
 '在',
 '不',
 '有',
 '都',
 '就',
 '.',
 '这',
 '、',
 '和',
 '没有',
 '还',
 '好',
 '酒店',
 '看',
 '人',
 '不错',
 '本书',
 '可以',
 '说',
 '买',
 '一个',
 '房间',
 '我们',
 '书',
 '到',
 '感觉',
 '还是',
 '自己',
 '让',
 '对',
 '给',
 '要',
 '就是',
 '但',
 '喜欢',
 '用',
 '？',
 '比较',
 '蒙牛',
 '上',
 '他',
 '去',
 '：',
 '你',
 '会',
 '~',
 '非常',
 '但是',
 '这个',
 '不是',
 '“',
 '；',
 '能',
 '”',
 '!',
 '没',
 '孩子',
 '她',
 '多',
 '中',
 '觉得',
 '什么',
 '又',
 '2',
 '服务',
 '时候',
 '太',
 '知道',
 '很多',
 '而且',
 '后',
 '住',
 '才',
 '问题',
 '这样',
 '1',
 '3',
 '想',
 '）',
 '啊',
 '小',
 '因为',
 '把',
 '时',
 '个',
 '吧',
 '有点',
 '（',
 '现在',
 '着',
 '大',
 '一般',
 '…',
 '还有',
 '与',
 '》',
 '《',
 '如果',
 '入住',
 '不过',
 '再',
 '过',
 '不能',
 '来',
 '内容',
 '所以',
 '更',
 '从',
 '作者',
 '得',
 '一本',
 '比',
 '看到',
 '里',
 '方便',
 '它',
 '已经',
 '被',
 '虽然',
 '月',
 '发现',
 '价格',
 '做',
 '4',
 '一',
 '最',
 '而',
 '功能',
 '朋友',
 '为',
 '-',
 '他们',
 '手机',
 '东西',
 '一样',
 '故事',
 '一些',
 '应该',
 '真的',
 '呢',
 '系统',
 '屏幕',
 '时间',
 '不好',
 '却',
 '

In [46]:
model.wv['e850']

array([-0.05756583,  0.02231228,  0.00898645,  0.01422738, -0.07697015,
        0.03624869, -0.00718278,  0.01807368, -0.01526734, -0.00125276,
       -0.00956459,  0.01881865, -0.01960497,  0.00984887,  0.04832486,
       -0.05783226,  0.04008583, -0.04387773, -0.03097921,  0.00214652,
       -0.01347909, -0.07189558,  0.01561494, -0.03998996,  0.03480006,
       -0.05072764, -0.02256131, -0.02937923, -0.09343294,  0.05585187,
       -0.05120449,  0.00627617, -0.01836586, -0.05712381, -0.0158513 ,
       -0.03096117,  0.00137817,  0.01002811,  0.00607665, -0.05212741,
       -0.00254409,  0.0097681 ,  0.0037785 ,  0.00713988,  0.08413785,
       -0.07585428,  0.01456052,  0.02751568, -0.05034705, -0.01953372,
        0.01315106,  0.02498071, -0.04901759, -0.02399664,  0.02921551,
        0.03054458, -0.00511247,  0.06131709,  0.0083101 ,  0.00974164,
        0.01348929,  0.01565018,  0.01292722, -0.02547618, -0.0032299 ,
        0.01232565,  0.04094412,  0.05440172,  0.01529548,  0.03

In [37]:
from gensim.models import  KeyedVectors

In [51]:
class  ss(object):
    def __init__(self,):
        pass
    def tt(self,target):
        s=[]
        self.target=1
        return target

In [52]:
tmp=ss()

In [54]:
tmp.tt(2)

2

In [59]:
import pickle
with open(r'D:\tensorflow\text_classification_self_learning\save\dictionary','rb') as f:
    token_dictionary = pickle.load(f)
    vocab_size = len(token_dictionary)
    #n_classes = y_train.shape[1]
    #print('vocab_size: {},classes_size: {}'.format(vocab_size,n_classes))

In [60]:
token_dictionary

{'E5400': 0,
 '质量': 1,
 '不错': 2,
 '不会': 3,
 '装': 4,
 '系统': 5,
 '的': 6,
 '朋友': 7,
 ',': 8,
 '一定': 9,
 '要': 10,
 '注意': 11,
 'linux': 12,
 '不好': 13,
 '弄': 14,
 '尽量': 15,
 '买': 16,
 '一个': 17,
 '带': 18,
 'windows': 19,
 '无聊': 20,
 '无病呻吟': 21,
 '照': 22,
 '她': 23,
 '说法': 24,
 '女人': 25,
 '最好': 26,
 '赶快': 27,
 '找个': 28,
 '有钱人': 29,
 '嫁': 30,
 '了': 31,
 '还': 32,
 '得': 33,
 '赶': 34,
 '在': 35,
 '20': 36,
 '几岁': 37,
 '时候': 38,
 '晕死': 39,
 '自己': 40,
 '认为': 41,
 '是': 42,
 '贵族': 43,
 '别人': 44,
 '就': 45,
 '当': 46,
 '你': 47,
 '有病': 48,
 '吧': 49,
 '棒子': 50,
 '就是': 51,
 '会': 52,
 '意淫': 53,
 '!': 54,
 '“': 55,
 '没有': 56,
 '条件': 57,
 '，': 58,
 '创造条件': 59,
 '也': 60,
 '上': 61,
 '”': 62,
 '这句': 63,
 '本': 64,
 '励精图治': 65,
 '一句': 66,
 '话': 67,
 '却': 68,
 '被': 69,
 '三菱': 70,
 '百万': 71,
 '像素': 72,
 '手机': 73,
 'M800': 74,
 '误解': 75,
 '成': 76,
 '虚荣心': 77,
 '意思': 78,
 '。': 79,
 '摄头': 80,
 '和': 81,
 '看似': 82,
 '很拉风': 83,
 '闪炫外': 84,
 '屏': 85,
 '太过': 86,
 '摊慕': 87,
 '虚荣': 88,
 '表现': 89,
 '虽然': 90,
 '不知': 91,
 '令': 92,


In [61]:
s='203 204 101 205 206 207 208   6 209  58 155   3 210 211 212   6 209  79\
 203 213 214 215   6 216 208  58 155   3 177 211 212 217 208   6 218  79\
 126  58  16  31 219 220 213  44'

In [63]:
for unit in s.split(' '):
    if unit !='' or unit !=' ':
        print(token_dictionary[int(unit)])

KeyError: 203